name: learning_layout
description: Learning Flutter Layout

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.15.8
  http: ^0.12.0+2
  flutter_bloc: ^0.21.0
  equatable: ^0.5.0
  geolocator: ^5.1.3
  location: ^2.3.5
  flutter_svg: ^0.14.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/lake.jpg
    - images/cloudy.png
    - images/logo.png
    - images/shoes_01.png
    - images/shoes_02.png
    - images/profile.png
    - images/store.png
    - images/360.png
    - images/adidas.png
    - images/cart.png
    - images/stadia/games/apex_legends.jpg
    - images/stadia/games/assassins_creed_odyssey.jpg
    - images/stadia/games/dead_cells.jpg
    - images/stadia/games/fortnite.jpg
    - images/stadia/games/no_mans_sky.jpeg
    - images/stadia/games/pubg.png
    - images/stadia/games/sekiro.png
    - images/stadia/games/stardew_valley.jpeg
    - images/stadia/images/stadia_logo.svg
    - images/stadia/players/gena_sedgwick.jpg
    - images/stadia/players/jeenie_duhe.jpg
    - images/stadia/players/jon_snow.jpeg
    - images/stadia/players/michelle_chong.jpg
    - images/stadia/players/trish_ammons.jpg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Regular.ttf

    - family: CustomIcons
      fonts:
        - asset: fonts/CustomIcon.ttf

    - family: Helvetica
      fonts:
        - asset: fonts/Helvetica-Bold-Font.ttf
          weight: 700

    - family: Montserrat-Medium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf

    - family: Montserrat-Bold
      fonts:
        - asset: fonts/Montserrat-Bold.ttf

    - family: Montserrat-SemiBold
      fonts:
        - asset: fonts/Montserrat-SemiBold.ttf

    - family: Oxygen
      fonts:
        - asset: fonts/Oxygen-Bold.ttf
          weight: 700
        - asset: fonts/Oxygen-Regular.ttf
          weight: 400
        - asset: fonts/Oxygen-Light.ttf
          weight: 300

